//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceConsumerWebApp.CalculateSoap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputQuery", Namespace="http://scalingapp.gear.host")]
    [System.SerializableAttribute()]
    public partial class InputQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double ScaledMinField;
        
        private double ScaledMaxField;
        
        private double RawMinField;
        
        private double RawMaxField;
        
        private System.Nullable<double> RawInputField;
        
        private System.Nullable<double> ScaledInputField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double ScaledMin {
            get {
                return this.ScaledMinField;
            }
            set {
                if ((this.ScaledMinField.Equals(value) != true)) {
                    this.ScaledMinField = value;
                    this.RaisePropertyChanged("ScaledMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double ScaledMax {
            get {
                return this.ScaledMaxField;
            }
            set {
                if ((this.ScaledMaxField.Equals(value) != true)) {
                    this.ScaledMaxField = value;
                    this.RaisePropertyChanged("ScaledMax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double RawMin {
            get {
                return this.RawMinField;
            }
            set {
                if ((this.RawMinField.Equals(value) != true)) {
                    this.RawMinField = value;
                    this.RaisePropertyChanged("RawMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double RawMax {
            get {
                return this.RawMaxField;
            }
            set {
                if ((this.RawMaxField.Equals(value) != true)) {
                    this.RawMaxField = value;
                    this.RaisePropertyChanged("RawMax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<double> RawInput {
            get {
                return this.RawInputField;
            }
            set {
                if ((this.RawInputField.Equals(value) != true)) {
                    this.RawInputField = value;
                    this.RaisePropertyChanged("RawInput");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<double> ScaledInput {
            get {
                return this.ScaledInputField;
            }
            set {
                if ((this.ScaledInputField.Equals(value) != true)) {
                    this.ScaledInputField = value;
                    this.RaisePropertyChanged("ScaledInput");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scalingapp.gear.host", ConfigurationName="CalculateSoap.CalculateWSSoap")]
    public interface CalculateWSSoap {
        
        // CODEGEN: Generating message contract since element name inputFromService from namespace http://scalingapp.gear.host is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://scalingapp.gear.host/CalculateService", ReplyAction="*")]
        ServiceConsumerWebApp.CalculateSoap.CalculateServiceResponse CalculateService(ServiceConsumerWebApp.CalculateSoap.CalculateServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scalingapp.gear.host/CalculateService", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceConsumerWebApp.CalculateSoap.CalculateServiceResponse> CalculateServiceAsync(ServiceConsumerWebApp.CalculateSoap.CalculateServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateService", Namespace="http://scalingapp.gear.host", Order=0)]
        public ServiceConsumerWebApp.CalculateSoap.CalculateServiceRequestBody Body;
        
        public CalculateServiceRequest() {
        }
        
        public CalculateServiceRequest(ServiceConsumerWebApp.CalculateSoap.CalculateServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://scalingapp.gear.host")]
    public partial class CalculateServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceConsumerWebApp.CalculateSoap.InputQuery inputFromService;
        
        public CalculateServiceRequestBody() {
        }
        
        public CalculateServiceRequestBody(ServiceConsumerWebApp.CalculateSoap.InputQuery inputFromService) {
            this.inputFromService = inputFromService;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateServiceResponse", Namespace="http://scalingapp.gear.host", Order=0)]
        public ServiceConsumerWebApp.CalculateSoap.CalculateServiceResponseBody Body;
        
        public CalculateServiceResponse() {
        }
        
        public CalculateServiceResponse(ServiceConsumerWebApp.CalculateSoap.CalculateServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://scalingapp.gear.host")]
    public partial class CalculateServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<double> CalculateServiceResult;
        
        public CalculateServiceResponseBody() {
        }
        
        public CalculateServiceResponseBody(System.Nullable<double> CalculateServiceResult) {
            this.CalculateServiceResult = CalculateServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculateWSSoapChannel : ServiceConsumerWebApp.CalculateSoap.CalculateWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculateWSSoapClient : System.ServiceModel.ClientBase<ServiceConsumerWebApp.CalculateSoap.CalculateWSSoap>, ServiceConsumerWebApp.CalculateSoap.CalculateWSSoap {
        
        public CalculateWSSoapClient() {
        }
        
        public CalculateWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculateWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceConsumerWebApp.CalculateSoap.CalculateServiceResponse ServiceConsumerWebApp.CalculateSoap.CalculateWSSoap.CalculateService(ServiceConsumerWebApp.CalculateSoap.CalculateServiceRequest request) {
            return base.Channel.CalculateService(request);
        }
        
        public System.Nullable<double> CalculateService(ServiceConsumerWebApp.CalculateSoap.InputQuery inputFromService) {
            ServiceConsumerWebApp.CalculateSoap.CalculateServiceRequest inValue = new ServiceConsumerWebApp.CalculateSoap.CalculateServiceRequest();
            inValue.Body = new ServiceConsumerWebApp.CalculateSoap.CalculateServiceRequestBody();
            inValue.Body.inputFromService = inputFromService;
            ServiceConsumerWebApp.CalculateSoap.CalculateServiceResponse retVal = ((ServiceConsumerWebApp.CalculateSoap.CalculateWSSoap)(this)).CalculateService(inValue);
            return retVal.Body.CalculateServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceConsumerWebApp.CalculateSoap.CalculateServiceResponse> ServiceConsumerWebApp.CalculateSoap.CalculateWSSoap.CalculateServiceAsync(ServiceConsumerWebApp.CalculateSoap.CalculateServiceRequest request) {
            return base.Channel.CalculateServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceConsumerWebApp.CalculateSoap.CalculateServiceResponse> CalculateServiceAsync(ServiceConsumerWebApp.CalculateSoap.InputQuery inputFromService) {
            ServiceConsumerWebApp.CalculateSoap.CalculateServiceRequest inValue = new ServiceConsumerWebApp.CalculateSoap.CalculateServiceRequest();
            inValue.Body = new ServiceConsumerWebApp.CalculateSoap.CalculateServiceRequestBody();
            inValue.Body.inputFromService = inputFromService;
            return ((ServiceConsumerWebApp.CalculateSoap.CalculateWSSoap)(this)).CalculateServiceAsync(inValue);
        }
    }
}
