//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASimpleAnalogueScaling
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class InputQuery
    {
        //public int QueryId { get; set; }


        //[Display(Name="Scaled Minimum")]
        //[Required(ErrorMessage ="Please provide Min", AllowEmptyStrings =false)]
        //public double ScaledMin { get; set; }
        //[Display(Name = "Scaled Max")]
        //[Required(ErrorMessage = "Please provide Max", AllowEmptyStrings = false)]
        //public double ScaledMax { get; set; }
        //[Display(Name = "Raw Minimum")]
        //[Required(ErrorMessage = "Please provide Min", AllowEmptyStrings = false)]
        //public double RawMin { get; set; }

        //[Display(Name = "Raw Maximum")]
        //[Required(ErrorMessage = "Please provide Max", AllowEmptyStrings = false)]
        //public double RawMax { get; set; }
        //public Nullable<double> RawInput { get; set; }
        //public Nullable<double> ScaledInput { get; set; }
    }
}
