//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASimpleAnalogueScaling
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class InputQuery
    {
        
        public int QueryId { get; set; }

        [Display(Name="Scaled Minimum")]
        [Required(ErrorMessage="Please enter Scaled Minimum Value. Eg: 100psi",AllowEmptyStrings=false)]
        public double ScaledMin { get; set; }

        [Display(Name = "Scaled Maximum")]
        [Required(ErrorMessage = "Please enter Scaled Maximum Value. Eg: 500psi", AllowEmptyStrings = false)]
        public double ScaledMax { get; set; }

        [Display(Name = "Raw Minimum")]
        [Required(ErrorMessage = "Please enter Raw Minimum Value. Eg: 4mA", AllowEmptyStrings = false)]
        public double RawMin { get; set; }

        [Display(Name = "Raw Maximum")]
        [Required(ErrorMessage = "Please enter Raw Maximum Value. Eg: 20mA", AllowEmptyStrings = false)]
        public double RawMax { get; set; }

        [Display(Name = "Raw Current Value")]
        [Required(ErrorMessage = "Please enter the Raw Current Value. Eg: 200psi", AllowEmptyStrings = true)]
        public double RawInput { get; set; }
    }
}
