//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScalingApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Part
    {

        public int PartId { get; set; }
        [StringLength(50,MinimumLength = 3)] //Setlenght
        [Required]
        [Display(Name = "Part Name")]
        public string PartName { get; set; }
        public string PartDescription { get; set; }
    }
}
